apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0


          args: ["start-dev"]   # más friendly para dev

          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin

            - name: KC_HOSTNAME
              value: devops.local
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME_STRICT
              value: "false"


            # puedes dejar KC_HOSTNAME y KC_HOSTNAME_PATH si tu Ingress ya funciona,
            # pero para simplificar: coméntalos de momento
            # - name: KC_HOSTNAME
            #   value: devops.local
            # - name: KC_HOSTNAME_PATH
            #   value: /auth




          # args: ["start"]

          # ports:
          #   - containerPort: 8080
          # env:
          #   - name: KEYCLOAK_ADMIN
          #     value: admin
          #   - name: KEYCLOAK_ADMIN_PASSWORD
          #     value: admin

          #   - name: KC_PROXY
          #     value: edge

          #   - name: KC_HOSTNAME
          #     value: devops.local

          #   - name: KC_HOSTNAME_PATH
          #     value: /auth

          #   - name: KC_HTTP_ENABLED
          #     value: "true"

          #   - name: KC_HOSTNAME_STRICT
          #     value: "false"
