apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-angular
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:
      containers:
        - name: frontend-angular
          image: frontend-angular:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: http://backend-api:8080
