name: CI/CD Kubernetes

on:
  push:
    branches: ["master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  KUBE_NAMESPACE: devops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- BACKEND ----------------
      - name: Build backend image
        run: |
         IMAGE_TAG="${GITHUB_SHA}"
         docker build \
          -t ghcr.io/${{ env.IMAGE_NAMESPACE }}/backend-api:${IMAGE_TAG} \
          ./backend-api-dotnet

      - name: Push backend image
        run: |
         IMAGE_TAG="${GITHUB_SHA}"
         docker push ghcr.io/${{ env.IMAGE_NAMESPACE }}/backend-api:${IMAGE_TAG}


      # ---------------- FRONTEND ----------------
      - name: Build frontend image
        run: |
         IMAGE_TAG="${GITHUB_SHA}"
         docker build \
         -t ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend-angular:${IMAGE_TAG} \
         ./frontend-angular

      - name: Push frontend image
        run: |
         IMAGE_TAG="${GITHUB_SHA}"
         docker push ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend-angular:${IMAGE_TAG}

