name: CI/CD Kubernetes

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  KUBE_NAMESPACE: devops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ---------------- BACKEND ----------------
    - name: Build backend image
      run: |
        docker build \
          -t ghcr.io/${{ env.IMAGE_NAMESPACE }}/backend-api:latest \
          ./backend-api-dotnet

    - name: Push backend image
      run: |
        docker push ghcr.io/${{ env.IMAGE_NAMESPACE }}/backend-api:latest

    # ---------------- FRONTEND ----------------
    - name: Build frontend image
      run: |
        docker build \
          -t ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend-angular:latest \
          ./frontend-angular

    - name: Push frontend image
      run: |
        docker push ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend-angular:latest

    # ---------------- DEPLOY ----------------
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Setup Helm
      uses: azure/setup-helm@v4

    - name: Deploy backend with Helm
      run: |
        helm upgrade --install backend helm/backend \
          --namespace ${{ env.KUBE_NAMESPACE }} \
          --set image.repository=ghcr.io/${{ env.IMAGE_NAMESPACE }}/backend-api

    - name: Deploy frontend with Helm
      run: |
        helm upgrade --install frontend helm/frontend \
          --namespace ${{ env.KUBE_NAMESPACE }} \
          --set image.repository=ghcr.io/${{ env.IMAGE_NAMESPACE }}/frontend-angular
